export enum ActionTypes {
  // Sign In Spotify
  SIGN_IN_SPOTIFY_START = 'SIGN_IN_SPOTIFY_START',
  SIGN_IN_SPOTIFY_SUCCESS = 'SIGN_IN_SPOTIFY_SUCCESS',
  SIGN_IN_SPOTIFY_FAIL = 'SIGN_IN_SPOTIFY_FAIL',
  // Sign In Firebase
  SIGN_IN_FIREBASE_START = 'SIGN_IN_FIREBASE_START',
  SIGN_IN_FIREBASE_SUCCESS = 'SIGN_IN_FIREBASE_SUCCESS',
  SIGN_IN_FIREBASE_FAIL = 'SIGN_IN_FIREBASE_FAIL',
  // Get New Releases
  GET_NEW_RELEASES_START = 'GET_NEW_RELEASES_START',
  GET_NEW_RELEASES_SUCCESS = 'GET_NEW_RELEASES_SUCCESS',
  GET_NEW_RELEASES_FAIL = 'GET_NEW_RELEASES_FAIL',
  // Find Tracks
  FIND_TRACKS_START = 'FIND_TRACKS_START',
  FIND_TRACKS_SUCCESS = 'FIND_TRACKS_SUCCESS',
  FIND_TRACKS_FAIL = 'FIND_TRACKS_FAIL',
  // Add Track to Library
  ADD_TRACK_START = 'ADD_TRACK_START',
  ADD_TRACK_SUCCESS = 'ADD_TRACK_SUCCESS',
  ADD_TRACK_FAIL = 'ADD_TRACK_FAIL',
  // Remove Track to Library
  REMOVE_TRACK_START = 'REMOVE_TRACK_START',
  REMOVE_TRACK_SUCCESS = 'REMOVE_TRACK_SUCCESS',
  REMOVE_TRACK_FAIL = 'REMOVE_TRACK_FAIL',
  // Notifications
  ADD_NOTIFICATION = 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION',
}
