export enum ActionTypes {
  // Sign In Spotify
  SIGN_IN_SPOTIFY_START = 'SIGN_IN_SPOTIFY_START',
  SIGN_IN_SPOTIFY_SUCCESS = 'SIGN_IN_SPOTIFY_SUCCESS',
  SIGN_IN_SPOTIFY_FAIL = 'SIGN_IN_SPOTIFY_FAIL',
  // Sign In Firebase
  SIGN_IN_FIREBASE_START = 'SIGN_IN_FIREBASE_START',
  SIGN_IN_FIREBASE_SUCCESS = 'SIGN_IN_FIREBASE_SUCCESS',
  SIGN_IN_FIREBASE_FAIL = 'SIGN_IN_FIREBASE_FAIL',
  // Sign Out
  SIGN_OUT = 'SIGN_OUT',
  // Refresh token
  REFRESH_TOKEN_START = 'REFRESH_TOKEN_START',
  REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL',
  // Get New Releases
  GET_NEW_RELEASES_START = 'GET_NEW_RELEASES_START',
  GET_NEW_RELEASES_SUCCESS = 'GET_NEW_RELEASES_SUCCESS',
  GET_NEW_RELEASES_FAIL = 'GET_NEW_RELEASES_FAIL',
  // Find Tracks
  FIND_TRACKS_START = 'FIND_TRACKS_START',
  FIND_TRACKS_SUCCESS = 'FIND_TRACKS_SUCCESS',
  FIND_TRACKS_FAIL = 'FIND_TRACKS_FAIL',
  // Update Library
  UPDATE_LIBRARY_START = 'UPDATE_LIBRARY_START',
  UPDATE_LIBRARY_SUCCESS = 'UPDATE_LIBRARY_SUCCESS',
  UPDATE_LIBRARY_FAIL = 'UPDATE_LIBRARY_FAIL',
  // Get Library
  GET_LIBRARY_START = 'GET_LIBRARY_START',
  GET_LIBRARY_SUCCESS = 'GET_LIBRARY_SUCCESS',
  GET_LIBRARY_FAIL = 'GET_LIBRARY_FAIL',
  // Notifications
  ADD_NOTIFICATION = 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION',
}
